pipeline {
    agent any

    stages {

        stage('Terraform Format') {
            steps {
                dir('netflix-devops/terraform') {
                    sh 'terraform fmt'
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir('netflix-devops/terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('netflix-devops/terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('netflix-devops/terraform') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('netflix-devops') {
                    sh 'docker build -t netflix-app -f docker/Dockerfile .'
                }
            }
        }
    }
}