pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = "035786426323"
        AWS_REGION = "us-east-1"
        ECR_REPO = "netflix-app"
        IMAGE_TAG = "latest"
        PEM_FILE = "/var/jenkins_home/netflix-key.pem"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Harshita079/netflix-devops-production.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('netflix-devops/terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('netflix-devops') {
                    sh '''
                    docker build -t $ECR_REPO:$IMAGE_TAG -f docker/Dockerfile .
                    '''
                }
            }
        }

        stage('Tag Docker Image') {
            steps {
                sh '''
                docker tag $ECR_REPO:$IMAGE_TAG \
                $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Push Image To ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin \
                $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

                docker push \
                $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy Application') {
            steps {

                script {

                    env.APP_IP = sh(
                        script: '''
                        cd netflix-devops/terraform
                        terraform output -raw app_ip
                        ''',
                        returnStdout: true
                    ).trim()

                    def IMAGE_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"

                    sh """
                    chmod 400 ${PEM_FILE}

                    ssh -i ${PEM_FILE} \
                    -o StrictHostKeyChecking=no \
                    ec2-user@${APP_IP} << EOF

                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin \
                    ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                    docker stop netflix || true
                    docker rm netflix || true

                    docker pull ${IMAGE_URI}

                    docker run -d -p 80:80 --name netflix ${IMAGE_URI}

                    EOF
                    """
                }
            }
        }
    }
}